DROP TABLE IF EXISTS USERS;
CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(200) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE
);

DROP TABLE IF EXISTS ROLE;
CREATE TABLE role (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT
);

DROP TABLE IF EXISTS USER_ROLE;
CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS PERMISSION;
CREATE TABLE PERMISSION (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    category VARCHAR(100),
    description TEXT
);

DROP TABLE IF EXISTS ROLE_PERMISSION;
CREATE TABLE ROLE_PERMISSION (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARYPRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permission(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS ENDPOINT;
CREATE TABLE endpoint (
    id BIGSERIAL PRIMARY KEY,
    path VARCHAR(300) NOT NULL,
    http_method VARCHAR(10) NOT NULL,
    module VARCHAR(100),
    service VARCHAR(100)
);

DROP TABLE IF EXISTS ENDPOINT_PERMISSION;
CREATE TABLE endpoint_permission (
    endpoint_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (endpoint_id, permission_id),
    FOREIGN KEY (endpoint_id) REFERENCES endpoint(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permission(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS ACL_OVERRIDE;
CREATE TABLE acl_override (
    user_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    granted BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (user_id, permission_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permission(id) ON DELETE CASCADE
);


